name: Update web components files

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  clone-and-build-web-component:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the quml-player
        run: git clone https://github.com/project-sunbird/sunbird-quml-player.git
      - name: Checkout to latest branch
        run: |
          cd sunbird-quml-player && git checkout release-5.2.0
          npm install && cd projects/quml-library && npm install
          npm run build-web-component
          ls ./dist/
      # - name: Install dependencies 
      # - name: Build Library and Web component
      # - name: See directory

